# Inserts a blank line between shell prompts
add_newline = true

format = "$all[>](bold green) "
right_format = "$character"

# This is hacky
[character]
success_symbol = ""
error_symbol = "[x](bold red)"
vimcmd_symbol = "[ NORMAL ](bold inverted fg:#8bc2f0)"
vimcmd_replace_one_symbol = "[ REPLACE ](bold inverted fg:#f8bd96)"
vimcmd_replace_symbol = "[ REPLACE ](bold inverted fg:#f8bd96)"
vimcmd_visual_symbol = "[ VISUAL ](bold inverted fg:#89dceb)"

[shell]
fish_indicator = "󰈺"
unknown_indicator = "mystery shell"
style = "blue bold"
disabled = false

[python]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "

[java]
symbol = " "

[c]
symbol = " "

[lua]
format = "via [ $version](bold blue) "
